version: "3.9"
services:
  backend:
    build: .
    container_name: musicsaver_backend
    networks:
      - musicsaver-network
  frontend:
    image: nginx:alpine
    container_name: musicsaver_frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - musicsaver-network
  redis:
    image: redis:latest
    container_name: musicsaver_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "50mb", "--maxmemory-policy", "allkeys-lru"]
    
networks:
  musicsaver-network:
    external: true
